// Generated by CoffeeScript 1.10.0

app.controller('inicioCrtl', [
  '$scope', '$http', '$timeout', '$location', function(scope, http, timeout, location2) {
    scope.form = [];
    scope.form = {};
    scope.datos = [];
    scope.datos = {};
    scope.datos2 = [];
    scope.datos2 = {};
    scope.range = [];
    scope.numpage = 1;
    scope.numpage2 = 1;
    scope.paginarPost = function(page){
      scope.numpage = scope.numpage + 1;
      page = scope.numpage;
      scope.listar(page, '');

    }
    scope.paginarPost2 = function(page){
      scope.numpage2 = scope.numpage2 + 1;
      page2 = scope.numpage2;
      scope.listarPopulares(page2, '');

    }
    scope.listarPopulares = function(page, filtro) {
      var data, result, url;
      data = {
        page: page,
        filtro: filtro
      };
      url = 'controller/noticia/listarpopulares.php';
      result = http.post(url, data);
      result.success(function(response) {
        var i, total;
        console.log(response);
        console.log("numero de pagina"+scope.numpage2)
        if (response !== "false") {
          scope.datos2 = response['listado'];
          i = 0;
          total2 = response['paginado'].total_paginas;
          while (i < total2) {
            scope.range.push(i);
            i++;
          }
          
        } else {
          scope.datos2 = {};
        }
        if (scope.numpage2 >= parseInt(total2)){
          $("#vermasPost2").fadeOut("slow");
        }
      });
      result.error(function(error) {
        console.log(error);
      });
    };
    scope.listar = function(page, filtro) {
      var data, result, url;
      data = {
        page: page,
        filtro: filtro
      };
      url = 'controller/noticia/listar.php';
      result = http.post(url, data);
      result.success(function(response) {
        var i, total;
        //console.log(response);
        //console.log("numero de pagina"+scope.numpage)
        if (response !== "false") {
          scope.datos = response['listado'];
          i = 0;
          total = response['paginado'].total_paginas;
          while (i < total) {
            scope.range.push(i);
            i++;
          }
          
        } else {
          scope.datos = {};
        }
        if (scope.numpage >= parseInt(total)){
          $("#vermasPost").fadeOut("slow");
        }
      });
      result.error(function(error) {
        console.log(error);
      });
    };
    scope.paginar = function(page) {
      scope.range = [];
      scope.listar(page, '');
    };
    scope.listar(scope.numpage, '');
    scope.listarPopulares(scope.numpage, '');
  }
]);

app.controller('categoriaNotCrtl', [
  '$scope', '$http', '$timeout', '$location', function(scope, http, timeout, location2) {
    scope.form = [];
    scope.form = {};
    scope.datos = [];
    scope.datos = {};
    scope.range = [];
    scope.numpage = 1;
    scope.paginarPost = function(codcategoria){
      scope.numpage = scope.numpage + 1;
      page = scope.numpage;
      scope.listar(page, '',codcategoria);
    }
    scope.listar = function(page, filtro,codcategoria) {
      var data, result, url;
      data = {
        page: page,
        filtro: filtro,
        codcategoria: codcategoria
      };
      url = 'controller/noticia/categoria_post.php';
      result = http.post(url, data);
      result.success(function(response) {
        var i, total;
        console.log(response);
        console.log("numero de pagina"+scope.numpage)
        if (response !== "false") {
          scope.datos = response['listado'];
          i = 0;
          total = response['paginado'].total_paginas;
          while (i < total) {
            scope.range.push(i);
            i++;
          }
          
        } else {
          scope.datos = {};
        }
        if (scope.numpage >= parseInt(total)){
          $("#mas").fadeOut("slow");
        }
      });
      result.error(function(error) {
        console.log(error);
      });
    };
    scope.paginar = function(page) {
      scope.range = [];
      scope.listar(page, '');
    };
  }
]);